apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaling
metadata:
  name: myhpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:
  minreplicas: 3
  maxreplicas: 4
    metrics:
      type: resources
      resources:
        type: cpu
        target:
          type: utilization
          averageutilization: 50
